

function init(self)
	self.pos = go.get_position()
end

local function round(x)
	local a = x % 1
	x = x - a
	if a < 0.5 then a = 0
	else a = 1 end
	return x + a
end

function on_message(self, message_id, message, sender)
	if message_id == hash("update pos") then
		self.pos = message.pos
		go.set_position(self.pos)
		label.set_text("#label", string.format("(%.1f, %.1f, %.3f)", self.pos.x, self.pos.y, self.pos.z))
	end
end
